import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsOptional,
  IsString,
  IsArray,
  IsMongoId,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';

export class OutletMenuItemDto {
  @ApiProperty({
    example: '60d5ecb86217152c9043e02d',
    description: 'Product ID reference',
  })
  @IsMongoId()
  productId: string;

  @ApiPropertyOptional({
    example: true,
    description: 'Whether the menu item is available',
    default: true,
  })
  @IsOptional()
  @Type(() => Boolean)
  @IsBoolean()
  isAvailable?: boolean = true;
}

export class CreateOutletDto {
  @ApiProperty({
    example: '60d5ecb86217152c9043e02d',
    description: 'Associated outlet type ID',
  })
  @IsMongoId()
  @IsNotEmpty()
  outletType: string;

  @ApiProperty({ example: 'Downtown Bistro', description: 'Outlet name' })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({
    example: 'A cozy bistro in the city center.',
    description: 'Outlet description',
  })
  @IsString()
  @IsNotEmpty()
  description: string;

  @ApiProperty({
    example: ['image1.jpg', 'image2.jpg'],
    description: 'Array of outlet image URLs',
  })
  @IsArray()
  @IsString({ each: true })
  @IsNotEmpty()
  images: string[];

  @ApiPropertyOptional({
    example: 'unique-qr-token-123',
    description:
      'Unique QR token for the outlet (generated by server if not provided)',
  })
  @IsString()
  @IsOptional()
  qrToken?: string;

  @ApiPropertyOptional({
    example: '60d5ecb86217152c9043e02d',
    description: 'Associated manager ID',
  })
  @IsMongoId()
  @IsOptional()
  managerId?: string;

  @ApiPropertyOptional({
    example: '60d5ecb86217152c9043e02d',
    description: 'Associated form ID',
  })
  @IsMongoId()
  @IsOptional()
  formId?: string;

  @ApiPropertyOptional({
    example: '60d5ecb86217152c9043e02d',
    description: 'Associated address ID',
  })
  @IsMongoId()
  @IsOptional()
  addressId?: string;

  @ApiPropertyOptional({
    example: '123 Main St, City',
    description: 'Address stored in outlet collection',
  })
  @IsString()
  @IsOptional()
  address?: string;

  @ApiPropertyOptional({
    example: [{ productId: '60d5ecb86217152c9043e02d', isAvailable: true }],
    description: 'Menu items for the outlet',
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => OutletMenuItemDto)
  menuItems?: OutletMenuItemDto[];

  @ApiPropertyOptional({
    example: '60d5ecb86217152c9043e02d',
    description: 'Associated product template ID',
  })
  @IsMongoId()
  @IsOptional()
  productTemplateId?: string;

  @ApiPropertyOptional({
    example: 'https://maps.google.com/...',
    description: 'Google Maps link for the outlet',
  })
  @IsString()
  @IsOptional()
  googleMapsLink?: string;

  @ApiPropertyOptional({
    example: ['Table 1', 'Table 2'],
    description: 'Tables in the outlet',
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  tables?: string[];
}
